---
title: "Teaching experience and philosophy"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>  

##### When I was an undergraduate student in biology at the University of California Santa Barbara, my home was in the Native American and Indigenous Studies Program in the office of Dr. Inés Talamantez. Inés welcomed my perspective as a first-generation immigrant, the first in my family to attend college, and a woman who struggled to merge traditional Mexican culture with Western academia. As an indigenous woman, Inés taught me that like much of institutionalized American culture, our perspective of scholarship is dominated by Eurocentric ideals. The lack of representation and inclusion deters many great minds from engaging in academia. This has largely shaped my teaching philosophy to engage students on a personal level in order to cultivate an inclusive and supportive setting.  

##### In my time as a graduate student at Cornell, I have been appointed teaching assistantships in plant evolution and plant biodiversity for plant science majors, and in general biology for non-majors:   
#####  + PLBIO 2300 Field Lab in Global Plant Biodiversity & Vegetation, Undergrad Course, SIPS Plant Biology Section, Cornell University. (Winter 2020)  
#####  + PLBIO 2300 Field Lab in Global Plant Biodiversity & Vegetation, Undergrad Course, SIPS Plant Biology Section, Cornell University. (Winter 2019)  
#####  + BIOG 1140 Foundations in Biology, Undergrad Course, Dept. of Neurobiology and Behavior, Cornell University. (Fall 2018)  
#####  + PLBIO 2410 Plant Biodiversity & Evolution, Undergrad Course, SIPS Plant Biology Section, Cornell University. (Fall 2017)  

<br>

##### As a senior undergraduate student at UCSB, I also assisted in courses focused on the intersection of religion and ecology:  
#####  + Teaching Assistant & Guest Lecturer. Native American Religious Traditions & Ecology, Undergrad Course, co-listed in Religious Studies Dept. and Environmental Studies Dept., University of California, Santa Barbara. (Summer and Fall 2011)  

